-- Course file repository ("Repozitorij"): metadata for uploaded files; binary content is
-- kept by the file-storage adapter (local FS), referenced by storage_key.
create table repozitorij_datoteka (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    filename varchar(255) not null,
    content_type varchar(255),
    size_bytes bigint not null default 0,
    storage_key varchar(255) not null,
    uploaded_by varchar(255),
    uploaded_at timestamp not null default current_timestamp
);

create index idx_repozitorij_course on repozitorij_datoteka (course_id);
