-- Invigilator assignments ("dežurstva"): which staff member supervises which
-- room of an assessment. Part of the "Dodjela asistenata" scheduling step.
create table exam_room_assistant (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exam (id),
  room_id bigint not null references room (id),
  app_user_id bigint not null references app_user (id)
);

create unique index uq_exam_room_assistant
  on exam_room_assistant (exam_id, room_id, app_user_id);
create index idx_exam_room_assistant_exam on exam_room_assistant (exam_id);
