-- Course reading list ("Literatura"): required ("obavezna") and recommended
-- ("preporučena") entries on the course page. Portable subset (H2 mode + PostgreSQL).
create table literatura_kolegija (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    title varchar(512) not null,
    author varchar(512) not null default '',
    mandatory boolean not null default true,
    ordinal integer not null default 0
);

create index idx_literatura_course on literatura_kolegija (course_id);
