-- Office hours ("konzultacije"): weekly slots published by teaching staff for a course.
-- Portable subset (H2 PostgreSQL mode + PostgreSQL).
create table konzultacije (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    staff_name varchar(255) not null default '',
    day_of_week varchar(32) not null,
    starts_at time not null,
    ends_at time not null,
    location varchar(255) not null default ''
);

create index idx_konzultacije_course on konzultacije (course_id);
