-- e-Portfolio entries (projects, achievements, skills) owned by a user.
-- Portable subset (H2 PostgreSQL mode + PostgreSQL).
create table eportfolio_unos (
    id bigint generated by default as identity primary key,
    user_id bigint not null references app_user (id),
    title varchar(255) not null,
    description text not null default '',
    category varchar(64) not null default '',
    link varchar(512) not null default '',
    created_at timestamp not null default current_timestamp
);

create index idx_eportfolio_user on eportfolio_unos (user_id);
