-- Demonstrators ("demonstrature"): students assigned to assist a course's laboratory exercises.
-- Portable subset (H2 PostgreSQL mode + PostgreSQL).
create table demonstrator (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    student_id bigint not null references student (id)
);

create unique index uq_demonstrator on demonstrator (course_id, student_id);
create index idx_demonstrator_course on demonstrator (course_id);
create index idx_demonstrator_student on demonstrator (student_id);
