-- Per-course grade thresholds (override of the global defaults). A course has at most one row;
-- absence means the configured defaults apply. Portable subset (H2 PostgreSQL mode + PostgreSQL).
create table grade_threshold (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    excellent integer not null,
    very_good integer not null,
    good integer not null,
    sufficient integer not null
);

create unique index uq_grade_threshold on grade_threshold (course_id);
