create table if not exists legacy_bootstrap_course (
  course_code varchar(32) primary key,
  title varchar(512) not null,
  workload_raw varchar(256) not null default '',
  description text not null default '',
  literature text not null default '',
  leaders text not null default '',
  instructors text not null default ''
);

create table if not exists legacy_bootstrap_enrollment (
  id bigint generated by default as identity primary key,
  jmbag varchar(16) not null,
  course_code varchar(32) not null,
  group_code varchar(64) not null default '',
  student_name varchar(255) not null default '',
  course_name varchar(512) not null default '',
  year_of_study integer not null default 1,
  source_line varchar(2048) not null default ''
);

create index if not exists idx_legacy_bootstrap_enrollment_jmbag
  on legacy_bootstrap_enrollment (jmbag);

create index if not exists idx_legacy_bootstrap_enrollment_course
  on legacy_bootstrap_enrollment (course_code);

create table if not exists legacy_bootstrap_schedule (
  id bigint generated by default as identity primary key,
  schedule_date date not null,
  starts_at time not null,
  duration_minutes integer not null,
  institution varchar(128) not null default '',
  room varchar(128) not null default '',
  course_code varchar(32) not null,
  groups_text varchar(1024) not null default ''
);

create index if not exists idx_legacy_bootstrap_schedule_course
  on legacy_bootstrap_schedule (course_code);

create index if not exists idx_legacy_bootstrap_schedule_date
  on legacy_bootstrap_schedule (schedule_date);

create table if not exists legacy_bootstrap_exam (
  id bigint generated by default as identity primary key,
  term_type varchar(32) not null,
  exam_date date not null,
  starts_at time not null,
  duration_hours integer not null,
  course_name varchar(512) not null default '',
  course_code varchar(32) not null
);

create index if not exists idx_legacy_bootstrap_exam_course
  on legacy_bootstrap_exam (course_code);

create index if not exists idx_legacy_bootstrap_exam_term
  on legacy_bootstrap_exam (term_type);

create table if not exists legacy_bootstrap_raw_line (
  id bigint generated by default as identity primary key,
  source_file varchar(255) not null,
  line_no integer not null,
  line_text text not null default ''
);

create index if not exists idx_legacy_bootstrap_raw_line_source
  on legacy_bootstrap_raw_line (source_file);
