-- Academic core: identities, roles, semesters, courses, staff, students,
-- enrollments, groups and rooms. Portable across H2 (PostgreSQL mode) and
-- PostgreSQL 16.

create table app_user (
  id bigint generated by default as identity primary key,
  username varchar(64) not null,
  password_hash varchar(100) not null,
  full_name varchar(255) not null,
  email varchar(255),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp
);

create unique index uq_app_user_username on app_user (username);

create table user_role (
  user_id bigint not null references app_user (id),
  role varchar(32) not null,
  primary key (user_id, role)
);

create table semester (
  code varchar(16) primary key,
  academic_year varchar(16) not null,
  term varchar(16) not null,
  starts_on date not null,
  ends_on date not null,
  active boolean not null default false
);

create table course (
  id bigint generated by default as identity primary key,
  code varchar(32) not null,
  name varchar(512) not null,
  semester_code varchar(16) not null references semester (code),
  ects integer not null default 0,
  description text,
  literature text
);

create unique index uq_course_code_semester on course (code, semester_code);
create index idx_course_semester on course (semester_code);

create table student (
  id bigint generated by default as identity primary key,
  user_id bigint not null references app_user (id),
  jmbag varchar(16) not null,
  study_program varchar(128),
  year_of_study integer not null default 1
);

create unique index uq_student_user on student (user_id);
create unique index uq_student_jmbag on student (jmbag);

create table course_staff (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  user_id bigint not null references app_user (id),
  role varchar(32) not null
);

create unique index uq_course_staff on course_staff (course_id, user_id, role);
create index idx_course_staff_course on course_staff (course_id);
create index idx_course_staff_user on course_staff (user_id);

create table student_group (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  group_code varchar(64) not null,
  type varchar(16) not null,
  category varchar(64),
  capacity integer not null default 0
);

create unique index uq_student_group on student_group (course_id, group_code, type);
create index idx_student_group_course on student_group (course_id);

create table enrollment (
  id bigint generated by default as identity primary key,
  student_id bigint not null references student (id),
  course_id bigint not null references course (id),
  enrolled_at timestamp not null default current_timestamp,
  status varchar(16) not null default 'ACTIVE'
);

create unique index uq_enrollment on enrollment (student_id, course_id);
create index idx_enrollment_course on enrollment (course_id);
create index idx_enrollment_student on enrollment (student_id);

create table group_membership (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null references enrollment (id),
  group_id bigint not null references student_group (id)
);

create unique index uq_group_membership on group_membership (enrollment_id, group_id);
create index idx_group_membership_group on group_membership (group_id);

create table room (
  id bigint generated by default as identity primary key,
  code varchar(64) not null,
  building varchar(128),
  capacity integer not null default 0,
  required_assistants integer not null default 1,
  has_computers boolean not null default false
);

create unique index uq_room_code on room (code);
