-- Assessments, grading, class schedules, the group-exchange workflow and the
-- exam seating model that the evolutionary scheduler will populate.
-- Portable across H2 (PostgreSQL mode) and PostgreSQL 16.

create table class_schedule (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  group_id bigint references student_group (id),
  type varchar(16) not null,
  room_id bigint references room (id),
  day_of_week varchar(16) not null,
  starts_at time not null,
  ends_at time not null,
  instructor varchar(255)
);

create index idx_class_schedule_course on class_schedule (course_id);
create index idx_class_schedule_group on class_schedule (group_id);

-- Flags / prerequisites ("zastavice") evaluated per student.
create table exam_flag (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  name varchar(255) not null,
  short_name varchar(64) not null,
  description text
);

create index idx_exam_flag_course on exam_flag (course_id);

-- Assessments / "provjere znanja".
create table exam (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  title varchar(255) not null,
  short_name varchar(64) not null,
  kind varchar(32) not null,
  starts_at timestamp,
  duration_minutes integer not null default 0,
  max_points numeric(7, 2) not null default 0,
  ordinal integer not null default 0,
  visibility varchar(32) not null default 'ALWAYS',
  locked boolean not null default false,
  prerequisite_flag_id bigint references exam_flag (id),
  published boolean not null default false
);

create index idx_exam_course on exam (course_id);

create table exam_registration (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exam (id),
  student_id bigint not null references student (id),
  registered_at timestamp not null default current_timestamp,
  status varchar(16) not null default 'REGISTERED'
);

create unique index uq_exam_registration on exam_registration (exam_id, student_id);
create index idx_exam_registration_exam on exam_registration (exam_id);

-- Rooms reserved for an assessment (capacity here may differ from physical).
create table exam_room (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exam (id),
  room_id bigint not null references room (id),
  capacity integer not null default 0,
  required_assistants integer not null default 1,
  reserved boolean not null default false
);

create unique index uq_exam_room on exam_room (exam_id, room_id);
create index idx_exam_room_exam on exam_room (exam_id);

-- Seating assignment produced by the scheduler: which student sits in which
-- room (and optionally seat / test-group label) for an assessment.
create table exam_seat (
  id bigint generated by default as identity primary key,
  exam_id bigint not null references exam (id),
  student_id bigint not null references student (id),
  room_id bigint not null references room (id),
  seat_no integer,
  test_group varchar(8)
);

create unique index uq_exam_seat on exam_seat (exam_id, student_id);
create index idx_exam_seat_exam on exam_seat (exam_id);
create index idx_exam_seat_room on exam_seat (exam_id, room_id);

create table grade_component (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  name varchar(255) not null,
  short_name varchar(64) not null,
  max_points numeric(7, 2) not null default 0,
  ordinal integer not null default 0
);

create unique index uq_grade_component on grade_component (course_id, short_name);
create index idx_grade_component_course on grade_component (course_id);

create table student_points (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  student_id bigint not null references student (id),
  component_id bigint references grade_component (id),
  exam_id bigint references exam (id),
  points numeric(7, 2) not null default 0,
  max_points numeric(7, 2) not null default 0,
  published boolean not null default false,
  entered_by varchar(64),
  entered_at timestamp not null default current_timestamp
);

create index idx_student_points_course_student on student_points (course_id, student_id);
create index idx_student_points_component on student_points (component_id);

create table grade (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  student_id bigint not null references student (id),
  final_grade integer not null,
  points_total numeric(7, 2) not null default 0,
  decided_by varchar(64),
  decided_at timestamp not null default current_timestamp
);

create unique index uq_grade on grade (course_id, student_id);

create table group_exchange_request (
  id bigint generated by default as identity primary key,
  course_id bigint not null references course (id),
  student_id bigint not null references student (id),
  from_group_id bigint references student_group (id),
  to_group_id bigint references student_group (id),
  status varchar(16) not null default 'PENDING',
  reason varchar(512),
  decided_by varchar(64),
  created_at timestamp not null default current_timestamp,
  decided_at timestamp
);

create index idx_group_exchange_course on group_exchange_request (course_id);
create index idx_group_exchange_student on group_exchange_request (student_id);

create table academic_audit_event (
  id bigint generated by default as identity primary key,
  occurred_at timestamp not null default current_timestamp,
  actor varchar(128) not null,
  action varchar(64) not null,
  entity_type varchar(64),
  entity_id varchar(64),
  details text
);

create index idx_academic_audit_occurred on academic_audit_event (occurred_at);
