-- Portal announcements ("obavijesti"): faculty-wide (course_id null) or per-course.
-- Written in the portable subset (H2 PostgreSQL mode + PostgreSQL) used by V4/V5.
create table obavijest (
    id bigint generated by default as identity primary key,
    course_id bigint references course (id),
    title varchar(255) not null,
    body text not null,
    author_name varchar(255),
    created_at timestamp not null default current_timestamp,
    pinned boolean not null default false
);

create index idx_obavijest_course on obavijest (course_id);
create index idx_obavijest_created on obavijest (created_at);

-- A couple of seeded faculty-wide notices so the portal is not empty on first run.
insert into obavijest (course_id, title, body, author_name, pinned)
values
    (null,
     'Dobro došli u FERKO',
     'Nova generacija FERKO portala je u radu. Provjere znanja, bodovi i rasporedi dostupni su kroz izbornik.',
     'sustav',
     true),
    (null,
     'Raspored ispitnih rokova',
     'Ispitni rokovi za ljetni semestar bit će objavljeni kroz administraciju provjera znanja na pojedinom kolegiju.',
     'studentska sluzba',
     false);
