-- Course evaluation surveys ("ankete"): a survey has Likert questions; students
-- submit 1..5 ratings; results are aggregated per question.
-- Portable subset (H2 PostgreSQL mode + PostgreSQL), matching V4/V5 style.
create table anketa (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    title varchar(255) not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp
);

create table anketa_pitanje (
    id bigint generated by default as identity primary key,
    anketa_id bigint not null references anketa (id),
    text varchar(500) not null,
    ordinal integer not null default 0
);

create table anketa_odgovor (
    id bigint generated by default as identity primary key,
    pitanje_id bigint not null references anketa_pitanje (id),
    ocjena integer not null,
    created_at timestamp not null default current_timestamp
);

create index idx_anketa_course on anketa (course_id);
create index idx_anketa_pitanje_anketa on anketa_pitanje (anketa_id);
create index idx_anketa_odgovor_pitanje on anketa_odgovor (pitanje_id);
