-- Per-course discussion ("Pitanja i problemi"): flat posts; a post may answer
-- another (parent_id) to form a question/answer pair.
-- Portable subset (H2 PostgreSQL mode + PostgreSQL), matching V4/V5 style.
create table forum_post (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    parent_id bigint references forum_post (id),
    author_name varchar(255),
    body text not null,
    created_at timestamp not null default current_timestamp
);

create index idx_forum_post_course on forum_post (course_id);
create index idx_forum_post_parent on forum_post (parent_id);
