-- Course content components ("KOMPONENTE"): titled content blocks on the course page
-- (O kolegiju, Literatura, Pravila ocjenjivanja, …). Portable subset (H2 mode + PostgreSQL).
create table komponenta_kolegija (
    id bigint generated by default as identity primary key,
    course_id bigint not null references course (id),
    title varchar(255) not null,
    content text not null,
    ordinal integer not null default 0,
    visible boolean not null default true
);

create index idx_komponenta_course on komponenta_kolegija (course_id);
