package hr.fer.zemris.ferko.application.usecase.admin;

import hr.fer.zemris.ferko.application.port.AppUserRepository;
import hr.fer.zemris.ferko.application.port.PasswordHasher;
import hr.fer.zemris.ferko.application.port.StudentRepository;
import hr.fer.zemris.ferko.application.usecase.admin.AdminStudentViews.AdminStudentProfileView;
import hr.fer.zemris.ferko.application.usecase.admin.AdminStudentViews.PasswordResetView;
import hr.fer.zemris.ferko.application.usecase.calendar.CalendarService;
import hr.fer.zemris.ferko.application.usecase.profile.AcademicSummaryService;
import hr.fer.zemris.ferko.application.usecase.student.StudentGradesService;
import hr.fer.zemris.ferko.domain.model.AppUser;
import hr.fer.zemris.ferko.domain.model.Role;
import hr.fer.zemris.ferko.domain.model.Student;
import java.util.List;
import java.util.Optional;

/**
 * Administrative view of any user's academic profile and an admin-only password reset. Aggregates
 * the existing per-user services by resolving the target user's username from their id, so an admin
 * can inspect a student's details, enrolment, grades and weekly schedule without impersonation.
 * Authorization is enforced at the web boundary (ADMIN only); this service performs no access
 * check.
 */
public class AdminStudentService {

  private final AppUserRepository userRepository;
  private final StudentRepository studentRepository;
  private final StudentGradesService studentGradesService;
  private final AcademicSummaryService academicSummaryService;
  private final CalendarService calendarService;
  private final PasswordHasher passwordHasher;

  public AdminStudentService(
      AppUserRepository userRepository,
      StudentRepository studentRepository,
      StudentGradesService studentGradesService,
      AcademicSummaryService academicSummaryService,
      CalendarService calendarService,
      PasswordHasher passwordHasher) {
    this.userRepository = userRepository;
    this.studentRepository = studentRepository;
    this.studentGradesService = studentGradesService;
    this.academicSummaryService = academicSummaryService;
    this.calendarService = calendarService;
    this.passwordHasher = passwordHasher;
  }

  /** The full administrative profile for the user with {@code userId}, or empty if no such user. */
  public Optional<AdminStudentProfileView> profile(long userId) {
    Optional<AppUser> maybeUser = userRepository.findById(userId);
    if (maybeUser.isEmpty()) {
      return Optional.empty();
    }
    AppUser user = maybeUser.get();
    String username = user.username();
    List<String> roles = user.roles().stream().map(Role::name).sorted().toList();
    Optional<Student> student = studentRepository.findByUserId(userId);

    return Optional.of(
        new AdminStudentProfileView(
            user.id(),
            username,
            user.fullName(),
            user.email(),
            user.active(),
            roles,
            student.isPresent(),
            student.map(Student::jmbag).orElse(null),
            student.map(Student::studyProgram).orElse(null),
            student.map(Student::yearOfStudy).orElse(0),
            student.isPresent() ? academicSummaryService.studySummary(username) : null,
            student.isPresent() ? studentGradesService.forStudent(username) : List.of(),
            calendarService.forUser(username).weekly()));
  }

  /**
   * Sets the user's password to {@code newPassword} (a one-time value generated by the caller),
   * persisting only its hash, and echoes it back so the admin can relay it once. The clear-text
   * password is never stored. Empty if no such user. Generation of the random value is the caller's
   * responsibility (kept at the web boundary so a cryptographic RNG is used).
   */
  public Optional<PasswordResetView> resetPassword(long userId, String newPassword) {
    Optional<AppUser> maybeUser = userRepository.findById(userId);
    if (maybeUser.isEmpty()) {
      return Optional.empty();
    }
    AppUser user = maybeUser.get();
    AppUser updated =
        new AppUser(
            user.id(),
            user.username(),
            passwordHasher.hash(newPassword),
            user.fullName(),
            user.email(),
            user.active(),
            user.createdAt(),
            user.roles());
    userRepository.save(updated);
    return Optional.of(new PasswordResetView(user.username(), newPassword));
  }
}
