-- Structure-cluster schema for adapter integration tests (mirrors V4).
create table app_user (
  id bigint generated by default as identity primary key,
  username varchar(64) not null,
  password_hash varchar(100) not null,
  full_name varchar(255) not null,
  email varchar(255),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp
);
create unique index uq_app_user_username on app_user (username);

create table user_role (
  user_id bigint not null,
  role varchar(32) not null,
  primary key (user_id, role)
);

create table semester (
  code varchar(16) primary key,
  academic_year varchar(16) not null,
  term varchar(16) not null,
  starts_on date not null,
  ends_on date not null,
  active boolean not null default false
);

create table course (
  id bigint generated by default as identity primary key,
  code varchar(32) not null,
  name varchar(512) not null,
  semester_code varchar(16) not null,
  ects integer not null default 0,
  description text,
  literature text
);

create table student (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  jmbag varchar(16) not null,
  study_program varchar(128),
  year_of_study integer not null default 1
);

create table course_staff (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  user_id bigint not null,
  role varchar(32) not null
);

create table student_group (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  group_code varchar(64) not null,
  type varchar(16) not null,
  category varchar(64),
  capacity integer not null default 0
);

create table enrollment (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  course_id bigint not null,
  enrolled_at timestamp not null default current_timestamp,
  status varchar(16) not null default 'ACTIVE'
);

create table group_membership (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null,
  group_id bigint not null
);

create table room (
  id bigint generated by default as identity primary key,
  code varchar(64) not null,
  building varchar(128),
  capacity integer not null default 0,
  required_assistants integer not null default 1,
  has_computers boolean not null default false
);

-- Assessment cluster (mirrors V5) for exam-repository tests.
create table exam (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  title varchar(255) not null,
  short_name varchar(64) not null,
  kind varchar(32) not null,
  starts_at timestamp,
  duration_minutes integer not null default 0,
  max_points numeric(7, 2) not null default 0,
  ordinal integer not null default 0,
  visibility varchar(32) not null default 'ALWAYS',
  locked boolean not null default false,
  prerequisite_flag_id bigint,
  published boolean not null default false
);

create table exam_registration (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  student_id bigint not null,
  registered_at timestamp not null default current_timestamp,
  status varchar(16) not null default 'REGISTERED'
);

create table exam_room (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  room_id bigint not null,
  capacity integer not null default 0,
  required_assistants integer not null default 1,
  reserved boolean not null default false
);

create table exam_seat (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  student_id bigint not null,
  room_id bigint not null,
  seat_no integer,
  test_group varchar(8)
);
