-- Structure-cluster schema for adapter integration tests (mirrors V4).
create table app_user (
  id bigint generated by default as identity primary key,
  username varchar(64) not null,
  password_hash varchar(100) not null,
  full_name varchar(255) not null,
  email varchar(255),
  active boolean not null default true,
  created_at timestamp not null default current_timestamp
);
create unique index uq_app_user_username on app_user (username);

create table user_role (
  user_id bigint not null,
  role varchar(32) not null,
  primary key (user_id, role)
);

create table semester (
  code varchar(16) primary key,
  academic_year varchar(16) not null,
  term varchar(16) not null,
  starts_on date not null,
  ends_on date not null,
  active boolean not null default false
);

create table course (
  id bigint generated by default as identity primary key,
  code varchar(32) not null,
  name varchar(512) not null,
  semester_code varchar(16) not null,
  ects integer not null default 0,
  description text,
  literature text
);

create table student (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  jmbag varchar(16) not null,
  study_program varchar(128),
  year_of_study integer not null default 1
);

create table course_staff (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  user_id bigint not null,
  role varchar(32) not null
);

create table student_group (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  group_code varchar(64) not null,
  type varchar(16) not null,
  category varchar(64),
  capacity integer not null default 0
);

create table enrollment (
  id bigint generated by default as identity primary key,
  student_id bigint not null,
  course_id bigint not null,
  enrolled_at timestamp not null default current_timestamp,
  status varchar(16) not null default 'ACTIVE'
);

create table group_membership (
  id bigint generated by default as identity primary key,
  enrollment_id bigint not null,
  group_id bigint not null
);

create table room (
  id bigint generated by default as identity primary key,
  code varchar(64) not null,
  building varchar(128),
  capacity integer not null default 0,
  required_assistants integer not null default 1,
  has_computers boolean not null default false
);

-- Assessment cluster (mirrors V5) for exam-repository tests.
create table exam (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  title varchar(255) not null,
  short_name varchar(64) not null,
  kind varchar(32) not null,
  starts_at timestamp,
  duration_minutes integer not null default 0,
  max_points numeric(7, 2) not null default 0,
  ordinal integer not null default 0,
  visibility varchar(32) not null default 'ALWAYS',
  locked boolean not null default false,
  prerequisite_flag_id bigint,
  published boolean not null default false
);

create table exam_registration (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  student_id bigint not null,
  registered_at timestamp not null default current_timestamp,
  status varchar(16) not null default 'REGISTERED'
);

create table exam_room (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  room_id bigint not null,
  capacity integer not null default 0,
  required_assistants integer not null default 1,
  reserved boolean not null default false
);

create table exam_seat (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  student_id bigint not null,
  room_id bigint not null,
  seat_no integer,
  test_group varchar(8)
);

create table exam_room_assistant (
  id bigint generated by default as identity primary key,
  exam_id bigint not null,
  room_id bigint not null,
  app_user_id bigint not null
);

create table literatura_kolegija (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  title varchar(512) not null,
  author varchar(512) not null default '',
  mandatory boolean not null default true,
  ordinal integer not null default 0
);

create table konzultacije (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  staff_name varchar(255) not null default '',
  day_of_week varchar(32) not null,
  starts_at time not null,
  ends_at time not null,
  location varchar(255) not null default ''
);

create table eportfolio_unos (
  id bigint generated by default as identity primary key,
  user_id bigint not null,
  title varchar(255) not null,
  description text not null default '',
  category varchar(64) not null default '',
  link varchar(512) not null default '',
  created_at timestamp not null default current_timestamp
);

create table grade_component (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  name varchar(255) not null,
  short_name varchar(64) not null,
  max_points numeric(7, 2) not null default 0,
  ordinal integer not null default 0
);

create table student_points (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  student_id bigint not null,
  component_id bigint,
  exam_id bigint,
  points numeric(7, 2) not null default 0,
  max_points numeric(7, 2) not null default 0,
  published boolean not null default false,
  entered_by varchar(64),
  entered_at timestamp not null default current_timestamp
);

create table grade (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  student_id bigint not null,
  final_grade integer not null,
  points_total numeric(7, 2) not null default 0,
  decided_by varchar(64),
  decided_at timestamp not null default current_timestamp
);

create table obavijest (
  id bigint generated by default as identity primary key,
  course_id bigint,
  title varchar(255) not null,
  body varchar(4000) not null,
  author_name varchar(255),
  created_at timestamp not null default current_timestamp,
  pinned boolean not null default false
);

create table class_schedule (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  group_id bigint,
  type varchar(16) not null,
  room_id bigint,
  day_of_week varchar(16) not null,
  starts_at time not null,
  ends_at time not null,
  instructor varchar(255)
);

create table anketa (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  title varchar(255) not null,
  active boolean not null default true,
  created_at timestamp not null default current_timestamp
);

create table anketa_pitanje (
  id bigint generated by default as identity primary key,
  anketa_id bigint not null,
  text varchar(500) not null,
  ordinal integer not null default 0
);

create table anketa_odgovor (
  id bigint generated by default as identity primary key,
  pitanje_id bigint not null,
  ocjena integer not null,
  created_at timestamp not null default current_timestamp
);

create table forum_post (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  parent_id bigint,
  author_name varchar(255),
  body varchar(4000) not null,
  created_at timestamp not null default current_timestamp
);

create table komponenta_kolegija (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  title varchar(255) not null,
  content varchar(4000) not null,
  ordinal integer not null default 0,
  visible boolean not null default true
);

create table repozitorij_datoteka (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  filename varchar(255) not null,
  content_type varchar(255),
  size_bytes bigint not null default 0,
  storage_key varchar(255) not null,
  uploaded_by varchar(255),
  uploaded_at timestamp not null default current_timestamp
);

create table group_exchange_request (
  id bigint generated by default as identity primary key,
  course_id bigint not null,
  student_id bigint not null,
  from_group_id bigint,
  to_group_id bigint,
  status varchar(16) not null default 'PENDING',
  reason varchar(512),
  decided_by varchar(64),
  created_at timestamp not null default current_timestamp,
  decided_at timestamp
);

create table academic_audit_event (
  id bigint generated by default as identity primary key,
  occurred_at timestamp not null default current_timestamp,
  actor varchar(128) not null,
  action varchar(64) not null,
  entity_type varchar(64),
  entity_id varchar(64),
  details text
);
