package hr.fer.zemris.ferko.webapi;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.info.BuildProperties;
import org.springframework.boot.test.context.SpringBootTest;

/**
 * Verifies the {@code build-info} goal produces {@code META-INF/build-info.properties}, which
 * Spring Boot loads into {@link BuildProperties} and serves through {@code /actuator/info}.
 */
@SpringBootTest
class ActuatorInfoTest {

  @Autowired(required = false)
  private BuildProperties buildProperties;

  @Test
  void buildInfoIsGeneratedAndLoaded() {
    assertNotNull(
        buildProperties, "build-info.properties should be generated by the build-info goal");
    assertEquals("ferko-web-api", buildProperties.getArtifact());
    assertNotNull(buildProperties.getVersion());
  }
}
